# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive\桌面\1902714-堇业先锋-【A05】基于人工智能的视觉识别技术【文思海辉】 -项目补充材料\APowerfulCamera.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5.QtGui import QBrush, QColor, QCursor, QFont, QPalette
from PyQt5.QtWidgets import QAbstractSpinBox, QCheckBox, QFrame, QLabel, QLineEdit, QPushButton, QSizePolicy, QSlider, QSpinBox, QStatusBar, QTabWidget, QTextEdit, QWidget
from PyQt5.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt

class Ui_Camera(object):
    def mousePressEvent(self, event):
        if event.button()==Qt.LeftButton:
            self.m_flag=True
            self.m_Position=event.globalPos()-self.pos() #获取鼠标相对窗口的位置
            event.accept()
            self.setCursor(QCursor(Qt.OpenHandCursor))  #更改鼠标图标
            
    def mouseMoveEvent(self, QMouseEvent):
        if Qt.LeftButton and self.m_flag:  
            self.move(QMouseEvent.globalPos()-self.m_Position)#更改窗口位置
            QMouseEvent.accept()
            
    def mouseReleaseEvent(self, QMouseEvent):
        self.m_flag=False
        self.setCursor(QCursor(Qt.ArrowCursor))
    def setupUi(self, Camera):
        self.setWindowFlags(Qt.FramelessWindowHint)  # 去掉标题栏的代码
        Camera.setObjectName("Camera")
        Camera.setWindowModality(Qt.NonModal)
        Camera.setEnabled(True)
        Camera.resize(1050, 736)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Camera.sizePolicy().hasHeightForWidth())
        Camera.setSizePolicy(sizePolicy)
        Camera.setMinimumSize(QSize(1050, 736))
        Camera.setMaximumSize(QSize(1050, 736))
        font = QFont()
        font.setFamily("微软雅黑 Light")
        Camera.setFont(font)
        Camera.setFocusPolicy(Qt.StrongFocus)
        Camera.setContextMenuPolicy(Qt.DefaultContextMenu)
        Camera.setAutoFillBackground(False)
        Camera.setStyleSheet("background:rgb(244, 245, 247)")
        Camera.setToolButtonStyle(Qt.ToolButtonIconOnly)
        Camera.setTabShape(QTabWidget.Rounded)
        Camera.setDockNestingEnabled(False)
        self.centralwidget = QWidget(Camera)
        self.centralwidget.setObjectName("centralwidget")
        self.set = QFrame(self.centralwidget)
        self.set.setGeometry(QRect(660, 60, 371, 411))
        self.set.setStyleSheet("border:0px solid rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background:white")
        self.set.setFrameShape(QFrame.NoFrame)
        self.set.setFrameShadow(QFrame.Raised)
        self.set.setObjectName("set")
        self.Die = QCheckBox(self.set)
        self.Die.setGeometry(QRect(130, 10, 71, 21))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Die.setFont(font)
        self.Die.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.Die.setObjectName("Die")
        self.R = QLabel(self.set)
        self.R.setGeometry(QRect(21, 50, 51, 16))
        self.R.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.R.setObjectName("R")
        self.RSld = QSlider(self.set)
        self.RSld.setGeometry(QRect(90, 47, 181, 22))
        self.RSld.setMaximumSize(QSize(999999, 16777215))
        self.RSld.setStyleSheet("QSlider::sub-page:horizontal\n"
"{\n"
"border: 1px solid #00ffFF; /* 边框颜色 */\n"
"\n"
"background:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #000000, stop:1 #0000FF); /* 颜色渐变*/\n"
"\n"
"}")
        self.RSld.setMaximum(255)
        self.RSld.setProperty("value", 255)
        self.RSld.setOrientation(Qt.Horizontal)
        self.RSld.setObjectName("RSld")
        self.RBx = QSpinBox(self.set)
        self.RBx.setGeometry(QRect(300, 46, 41, 22))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.RBx.setFont(font)
        self.RBx.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.RBx.setLayoutDirection(Qt.LeftToRight)
        self.RBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.RBx.setWrapping(False)
        self.RBx.setFrame(True)
        self.RBx.setAlignment(Qt.AlignCenter)
        self.RBx.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.RBx.setAccelerated(False)
        self.RBx.setCorrectionMode(QAbstractSpinBox.CorrectToPreviousValue)
        self.RBx.setMaximum(255)
        self.RBx.setProperty("value", 255)
        self.RBx.setObjectName("RBx")
        self.GBx = QSpinBox(self.set)
        self.GBx.setGeometry(QRect(300, 84, 41, 22))
        self.GBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.GBx.setAlignment(Qt.AlignCenter)
        self.GBx.setMaximum(255)
        self.GBx.setProperty("value", 255)
        self.GBx.setObjectName("GBx")
        self.G = QLabel(self.set)
        self.G.setGeometry(QRect(20, 88, 51, 16))
        self.G.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.G.setObjectName("G")
        self.GSld = QSlider(self.set)
        self.GSld.setGeometry(QRect(90, 85, 181, 22))
        self.GSld.setMaximum(255)
        self.GSld.setProperty("value", 255)
        self.GSld.setOrientation(Qt.Horizontal)
        self.GSld.setObjectName("GSld")
        self.BSld = QSlider(self.set)
        self.BSld.setGeometry(QRect(90, 127, 181, 22))
        self.BSld.setMaximum(255)
        self.BSld.setProperty("value", 255)
        self.BSld.setOrientation(Qt.Horizontal)
        self.BSld.setObjectName("BSld")
        self.B = QLabel(self.set)
        self.B.setGeometry(QRect(21, 130, 41, 16))
        self.B.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.B.setObjectName("B")
        self.BBx = QSpinBox(self.set)
        self.BBx.setGeometry(QRect(300, 126, 41, 22))
        self.BBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.BBx.setAlignment(Qt.AlignCenter)
        self.BBx.setMaximum(255)
        self.BBx.setProperty("value", 255)
        self.BBx.setObjectName("BBx")
        self.BG = QLabel(self.set)
        self.BG.setGeometry(QRect(21, 171, 51, 21))
        self.BG.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.BG.setObjectName("BG")
        self.BGSld = QSlider(self.set)
        self.BGSld.setGeometry(QRect(90, 170, 181, 22))
        self.BGSld.setMinimum(-20)
        self.BGSld.setMaximum(20)
        self.BGSld.setProperty("value", 0)
        self.BGSld.setOrientation(Qt.Horizontal)
        self.BGSld.setObjectName("BGSld")
        self.ZY = QLabel(self.set)
        self.ZY.setGeometry(QRect(20, 211, 51, 20))
        self.ZY.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.ZY.setObjectName("ZY")
        self.ZYSld = QSlider(self.set)
        self.ZYSld.setGeometry(QRect(90, 210, 181, 22))
        self.ZYSld.setMinimum(0)
        self.ZYSld.setMaximum(128)
        self.ZYSld.setProperty("value", 64)
        self.ZYSld.setOrientation(Qt.Horizontal)
        self.ZYSld.setObjectName("ZYSld")
        self.ZYBx = QSpinBox(self.set)
        self.ZYBx.setGeometry(QRect(300, 210, 41, 22))
        self.ZYBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.ZYBx.setAlignment(Qt.AlignCenter)
        self.ZYBx.setMinimum(0)
        self.ZYBx.setMaximum(128)
        self.ZYBx.setProperty("value", 64)
        self.ZYBx.setObjectName("ZYBx")
        self.LDSld = QSlider(self.set)
        self.LDSld.setGeometry(QRect(90, 250, 181, 22))
        self.LDSld.setMinimum(-100)
        self.LDSld.setMaximum(100)
        self.LDSld.setOrientation(Qt.Horizontal)
        self.LDSld.setObjectName("LDSld")
        self.LDBx = QSpinBox(self.set)
        self.LDBx.setGeometry(QRect(300, 250, 41, 22))
        self.LDBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.LDBx.setAlignment(Qt.AlignCenter)
        self.LDBx.setMinimum(-100)
        self.LDBx.setMaximum(100)
        self.LDBx.setProperty("value", 0)
        self.LDBx.setObjectName("LDBx")
        self.LD = QLabel(self.set)
        self.LD.setGeometry(QRect(20, 251, 51, 20))
        self.LD.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.LD.setObjectName("LD")
        self.DBSld = QSlider(self.set)
        self.DBSld.setGeometry(QRect(90, 290, 181, 22))
        self.DBSld.setMinimum(0)
        self.DBSld.setMaximum(100)
        self.DBSld.setProperty("value", 50)
        self.DBSld.setOrientation(Qt.Horizontal)
        self.DBSld.setObjectName("DBSld")
        self.DBBx = QSpinBox(self.set)
        self.DBBx.setGeometry(QRect(300, 290, 41, 22))
        self.DBBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.DBBx.setAlignment(Qt.AlignCenter)
        self.DBBx.setMinimum(0)
        self.DBBx.setMaximum(100)
        self.DBBx.setProperty("value", 50)
        self.DBBx.setObjectName("DBBx")
        self.DB = QLabel(self.set)
        self.DB.setGeometry(QRect(20, 291, 51, 20))
        self.DB.setStyleSheet("font: 9pt \"微软雅黑\"\n"
"")
        self.DB.setObjectName("DB")
        self.LJ = QLabel(self.set)
        self.LJ.setGeometry(QRect(20, 336, 71, 20))
        self.LJ.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.LJ.setObjectName("LJ")
        self.LJTx = QLineEdit(self.set)
        self.LJTx.setGeometry(QRect(100, 330, 171, 31))
        self.LJTx.setStyleSheet("border:1px solid rgb(11, 62, 211);\n"
"border-radius: 4px;\n"
"font: 9pt \"微软雅黑\";")
        self.LJTx.setReadOnly(True)
        self.LJTx.setObjectName("LJTx")
        self.LJBut = QPushButton(self.set)
        self.LJBut.setGeometry(QRect(296, 330, 51, 28))
        self.LJBut.setStyleSheet("background:rgb(244, 245, 247)")
        self.LJBut.setObjectName("LJBut")
        self.BGBx = QSpinBox(self.set)
        self.BGBx.setGeometry(QRect(300, 170, 41, 22))
        self.BGBx.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.BGBx.setAlignment(Qt.AlignCenter)
        self.BGBx.setMinimum(-20)
        self.BGBx.setMaximum(20)
        self.BGBx.setProperty("value", 0)
        self.BGBx.setObjectName("BGBx")
        self.label = QLabel(self.set)
        self.label.setGeometry(QRect(80, 375, 191, 21))
        self.label.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.Local = QCheckBox(self.set)
        self.Local.setGeometry(QRect(20, 10, 71, 21))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Local.setFont(font)
        self.Local.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.Local.setObjectName("Local")
        self.label_2 = QLabel(self.set)
        self.label_2.setGeometry(QRect(230, 14, 54, 12))
        self.label_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.quick = QSpinBox(self.set)
        self.quick.setGeometry(QRect(300, 10, 41, 22))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        self.quick.setFont(font)
        self.quick.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.quick.setLayoutDirection(Qt.LeftToRight)
        self.quick.setStyleSheet("QSpinBox\n"
"{\n"
"    border:1px solid rgb(11, 62, 211);\n"
"    border-radius: 4px;\n"
"}\n"
"QSpinBox::up-button,QSpinBox::down-button\n"
"{\n"
"    width:0px;\n"
"}")
        self.quick.setWrapping(False)
        self.quick.setFrame(True)
        self.quick.setAlignment(Qt.AlignCenter)
        self.quick.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.quick.setAccelerated(False)
        self.quick.setCorrectionMode(QAbstractSpinBox.CorrectToPreviousValue)
        self.quick.setMaximum(8)
        self.quick.setProperty("value", 3)
        self.quick.setObjectName("quick")
        self.cam = QLabel(self.centralwidget)
        self.cam.setGeometry(QRect(20, 60, 611, 411))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam.setFont(font)
        self.cam.setStyleSheet("border:0px solid rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background:white\n"
"")
        self.cam.setScaledContents(True)
        self.cam.setObjectName("cam")
        self.frame = QFrame(self.centralwidget)
        self.frame.setGeometry(QRect(660, 490, 371, 211))
        self.frame.setStyleSheet("border:0px solid rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background:white")
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Start = QPushButton(self.frame)
        self.Start.setEnabled(True)
        self.Start.setGeometry(QRect(20, 70, 95, 91))
        palette = QPalette()
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.Start.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setStyleSheet("QPushButton{\n"
"    background-image: url(./icon/浅蓝色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(223, 224, 227)\n"
"} \n"
"QPushButton:!enabled\n"
"{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color: rgb(223, 224, 227);\n"
"} ")
        self.Start.setAutoRepeat(False)
        self.Start.setObjectName("Start")
        self.Stop = QPushButton(self.frame)
        self.Stop.setGeometry(QRect(134, 65, 96, 99))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Stop.setFont(font)
        self.Stop.setStyleSheet("QPushButton{\n"
"    background-image: url(./icon/蓝色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(223, 224, 227)\n"
"} \n"
"QPushButton:!enabled\n"
"{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color: rgb(223, 224, 227);\n"
"} ")
        self.Stop.setObjectName("Stop")
        self.Record = QPushButton(self.frame)
        self.Record.setGeometry(QRect(250, 65, 95, 98))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Record.setFont(font)
        self.Record.setStyleSheet("QPushButton{\n"
"    background-image: url(./icon/紫色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(52, 55, 61)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color:rgb(223, 224, 227)\n"
"} \n"
"QPushButton:!enabled\n"
"{\n"
"    background-image: url(./icon/灰色.jpg);\n"
"    background-position:Center;\n"
"    color: rgb(223, 224, 227);\n"
"} ")
        self.Record.setObjectName("Record")
        self.cam_4 = QLabel(self.frame)
        self.cam_4.setGeometry(QRect(10, 0, 361, 41))
        palette = QPalette()
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_4.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_4.setFont(font)
        self.cam_4.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(52, 55, 61)")
        self.cam_4.setObjectName("cam_4")
        self.cam_6 = QLabel(self.frame)
        self.cam_6.setGeometry(QRect(-10, 0, 31, 41))
        palette = QPalette()
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_6.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_6.setFont(font)
        self.cam_6.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(245, 56, 54)")
        self.cam_6.setObjectName("cam_6")
        self.cam_2 = QLabel(self.centralwidget)
        self.cam_2.setGeometry(QRect(33, 10, 191, 41))
        palette = QPalette()
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_2.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_2.setFont(font)
        self.cam_2.setStyleSheet("color:rgb(52, 55, 61)")
        self.cam_2.setObjectName("cam_2")
        self.Exit = QPushButton(self.centralwidget)
        self.Exit.setGeometry(QRect(1004, 6, 21, 41))
        palette = QPalette()
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(223, 224, 227))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.Exit.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Exit.setFont(font)
        self.Exit.setFocusPolicy(Qt.NoFocus)
        self.Exit.setStyleSheet("color: rgb(223,224,227);\n"
"border:0px solid rgb(255, 255, 255);\n"
"font: 16pt \"微软雅黑\";\n"
"")
        self.Exit.setAutoDefault(False)
        self.Exit.setObjectName("Exit")
        self.cam_7 = QLabel(self.centralwidget)
        self.cam_7.setGeometry(QRect(13, 10, 21, 41))
        palette = QPalette()
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(244, 245, 247))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_7.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_7.setFont(font)
        self.cam_7.setStyleSheet("color:rgb(245, 56, 54)")
        self.cam_7.setObjectName("cam_7")
        self.data_2 = QFrame(self.centralwidget)
        self.data_2.setGeometry(QRect(20, 490, 291, 221))
        self.data_2.setStyleSheet("border:0px solid rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background:white")
        self.data_2.setFrameShadow(QFrame.Raised)
        self.data_2.setObjectName("data_2")
        self.Info_2 = QTextEdit(self.data_2)
        self.Info_2.setGeometry(QRect(13, 55, 261, 152))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Info_2.setFont(font)
        self.Info_2.setStyleSheet("border:1px solid rgb(11, 62, 211);\n"
"border-radius: 4px;")
        self.Info_2.setReadOnly(True)
        self.Info_2.setObjectName("Info_2")
        self.cam_8 = QLabel(self.data_2)
        self.cam_8.setGeometry(QRect(10, 0, 241, 41))
        palette = QPalette()
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_8.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_8.setFont(font)
        self.cam_8.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(52, 55, 61)")
        self.cam_8.setObjectName("cam_8")
        self.cam_9 = QLabel(self.data_2)
        self.cam_9.setGeometry(QRect(-10, 0, 31, 41))
        palette = QPalette()
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_9.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_9.setFont(font)
        self.cam_9.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(245, 56, 54)")
        self.cam_9.setObjectName("cam_9")
        self.data = QFrame(self.centralwidget)
        self.data.setGeometry(QRect(340, 490, 291, 221))
        self.data.setStyleSheet("border:0px solid rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background:white")
        self.data.setFrameShadow(QFrame.Raised)
        self.data.setObjectName("data")
        self.Info = QTextEdit(self.data)
        self.Info.setGeometry(QRect(13, 55, 261, 152))
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Info.setFont(font)
        self.Info.setStyleSheet("border:1px solid rgb(11, 62, 211);\n"
"border-radius: 4px;")
        self.Info.setReadOnly(True)
        self.Info.setObjectName("Info")
        self.cam_3 = QLabel(self.data)
        self.cam_3.setGeometry(QRect(10, 0, 241, 41))
        palette = QPalette()
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(52, 55, 61))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_3.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_3.setFont(font)
        self.cam_3.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(52, 55, 61)")
        self.cam_3.setObjectName("cam_3")
        self.cam_5 = QLabel(self.data)
        self.cam_5.setGeometry(QRect(-10, 0, 21, 41))
        palette = QPalette()
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(245, 56, 54))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.cam_5.setPalette(palette)
        font = QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cam_5.setFont(font)
        self.cam_5.setStyleSheet("border:2px solid rgb(255,255,255);\n"
"border-radius: 4px;\n"
"border-bottom-color: rgb(244, 245, 247);\n"
"color:rgb(245, 56, 54)")
        self.cam_5.setObjectName("cam_5")
        Camera.setCentralWidget(self.centralwidget)

        self.retranslateUi(Camera)
        QMetaObject.connectSlotsByName(Camera)

    def retranslateUi(self, Camera):
        _translate = QCoreApplication.translate
        Camera.setWindowTitle(_translate("Camera", "Camera"))
        self.Die.setText(_translate("Camera", "灰度模式"))
        self.R.setText(_translate("Camera", "Red"))
        self.G.setText(_translate("Camera", "Green"))
        self.B.setText(_translate("Camera", "Blue"))
        self.BG.setText(_translate("Camera", "曝光"))
        self.ZY.setText(_translate("Camera", "增益"))
        self.LD.setText(_translate("Camera", "亮度"))
        self.DB.setText(_translate("Camera", "对比"))
        self.LJ.setText(_translate("Camera", "保存路径"))
        self.LJTx.setText(_translate("Camera", "请选择保存路径"))
        self.LJBut.setText(_translate("Camera", "..."))
        self.label.setText(_translate("Camera", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Local.setText(_translate("Camera", "本地模式"))
        self.label_2.setText(_translate("Camera", "检测速度："))
        self.cam.setText(_translate("Camera", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; color:#dfe0e3;\">输入图像</span></p></body></html>"))
        self.Start.setText(_translate("Camera", "开启"))
        self.Stop.setText(_translate("Camera", "暂停"))
        self.Record.setText(_translate("Camera", "录像"))
        self.cam_4.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">操作按钮</span></p></body></html>"))
        self.cam_6.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">丨</span></p></body></html>"))
        self.cam_2.setText(_translate("Camera", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">智能安全帽检测系统</span></p></body></html>"))
        self.Exit.setText(_translate("Camera", "×"))
        self.cam_7.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">丨</span></p></body></html>"))
        self.Info_2.setHtml(_translate("Camera", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cam_8.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">检测结果</span></p></body></html>"))
        self.cam_9.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">丨</span></p></body></html>"))
        self.Info.setHtml(_translate("Camera", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cam_3.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">数据显示</span></p></body></html>"))
        self.cam_5.setText(_translate("Camera", "<html><head/><body><p><span style=\" font-size:10pt;\">丨</span></p></body></html>"))
